config/routes.rb
Rails.application.routes.draw do

  get 'login/index'
  root 'login#index'
  post 'login/login_page'
  get 'login/logout'
  resources :users
  resources :diaries
  get 'get_image/:id', to: 'diaries#get_image'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/diary.rb
class Diary < ApplicationRecord
    belongs_to :user
    validates :title , :message ,presence: true
    validates :title, length: { maximum: 20 }
end

app/models/question.rb
class Question < ApplicationRecord
    validates :question, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :diaries, dependent: :destroy
    validates :name , :password, :email ,presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
    def index
        if params[:each].nil?
          @diaries = Diary.all
          @q = Question.all
        else
          @diaries = Diary.where(user_id: params[:each])
          @q = Question.all
        end
    end
    
    def new
        @diary = Diary.new
        @question = Question.offset(rand(Question.count)).first.id
    end
    
    def create
        @question = params[:question]
        if  params[:diary][:file].present?
            file = params[:diary][:file].read
            @diary = Diary.new(title: params[:diary][:title], message: params[:diary][:message],file: file, date: Time.current, qid: params[:diary][:qid],user_id: session[:login_uid])
            if @diary.save
                flash[:notice] = '1レコード追加しました'
                redirect_to diaries_path
            else
                render "new" 
            end
        else
            @diary = Diary.new(title: params[:diary][:title], message: params[:diary][:message],date: Time.current, qid: params[:diary][:qid],user_id: session[:login_uid])
            if @diary.save
                flash[:notice] = '1レコード追加しました'
                redirect_to diaries_path
            else
                render "new"
            end
        end
    end
    
    def get_image
        diary = Diary.find(params[:id]) #↓詳細は説明を後述する
        send_data diary.file, disposition: :inline, type: 'image/jpg'
    end
    
    def destroy
        diary = Diary.find(params[:id])
        diary.destroy
        flash[:notice] = '1レコード削除しました'
        redirect_to diaries_path
    end
    
    def edit
        @diary = Diary.find(params[:id])
    end
    
    def update
        diary = Diary.find(params[:id])
        if  params[:diary][:file].present?
          file = params[:diary][:file].read
          diary.update(title: params[:diary][:title], message: params[:diary][:message], file: file, date: Time.current, qid: params[:diary][:qid],user_id: session[:login_uid])
          flash[:notice] = '1レコード編集しました'
          redirect_to diaries_path
        else
          diary.update(title: params[:diary][:title], message: params[:diary][:message], date: Time.current, qid: params[:diary][:qid],user_id: session[:login_uid])
          flash[:notice] = '1レコード編集しました'
          redirect_to diaries_path
        end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    if session[:login_uid]
      render 'index'
    else
      render 'login_page'
    end
  end
  
  def login_page
    if User.find_by(email: params[:email])
      user = User.find_by(email: params[:email])
      if user.name == params[:name]
        userpassword = user.password
        if BCrypt::Password.new(userpassword) == params[:password]
          u_id = user.id
          session[:login_uid] = u_id
          redirect_to diaries_path
        else
          render 'error'
        end
      else
        render 'error'
      end
    else
      render 'error'
    end
  end
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create 
    require 'bcrypt'
    @name = params[:user][:name]
    @password = params[:user][:password]
    @userpass = BCrypt::Password.create(@password)
    @email = params[:user][:email]
    @user = User.new(name: @name,password: @userpass,email: @email)
    if @user.save
      redirect_to root_path
      # Handle a successful save.
    else
      render 'new'
    end
    
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to login_logout_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diarys_helper.rb
module DiarysHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/edit.html.erb
<div id="wrapper">
        <div id="header">
           <%= image_tag 'rogo4.jpg', class: 'rogo' %>
        </div>
        
        <div id="main">
            <div id="menu">
                <p><%= link_to 'ホームへ', diaries_path, class: 'button02' %></p><br>
                <p><%= link_to 'ログアウト',  login_logout_path, class: 'button02' %></p><br>
            </div>
            
        　　<div id="contents">
                <% if @diary.errors.present? %>
                <h3>エラーがあります。</h3>
                <ul>
                <% @diary.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
                </ul>
                <% end %>
                
                <p><%= form_for @diary, url: {action: :update} do |f| %>
                <p><%= f.label :title, 'タイトル' %></p>
                <%= f.text_field :title, placeholder: "title"%></p>
                <p><%= f.label :message, Question.find_by(id: @diary.qid).question %></p>
                <p><%= f.text_area :message,size: "70x10",placeholder: "what is about?" %></p>
                <p><%= f.label :file, 'ファイル' %></p>
                <p><%= f.file_field :file %></p>
                <br>
                <%= f.hidden_field :qid, value: @diary.qid %>
                <%= f.hidden_field :question, :value => @diary.qid %>
                <p><%= f.submit '更新' %></p>
                <% end %>
            </div>
        </div>
        
        <div id="footer">
           (c)copy right
       </div>
</div>

app/views/diaries/index.html.erb
<div id="wrapper">
    <div id="header">
        <%= image_tag 'rogo4.jpg', class: 'rogo' %>
    </div>

    
    <div id="main">
      <div id="menu">
        
        <label class="open" for="pop-up">
          <div class="text"><div class="button03">
          使い方を見る</div></div>
        </label>
              
        <input type="checkbox" id="pop-up">
          <div class="overlay">
            <div class="window">
            <label class="close" for="pop-up">×</label>
                  今日はどんな一日でしたか？<br>
              		出来事を記録してみましょう。<br>
              		書く話題に困ったら、入力フォーム上部に表示されるお題を参考にしてみてくださいね。<br>
            </div>
          </div><br>
          
          
        <p><%= link_to '新規投稿', '/diaries/new', class: 'button01' %></p><br>
        <p><%= link_to 'ユーザ一覧', users_path, class: 'button02' %></p><br>
        <p><%= link_to 'ログアウト',  login_logout_path, class: 'button02' %></p><br>
        <p>　</p>
        <h3>お題一覧</h3>
        <% @q.each do |e| %>
          <div align="left"><p><%= link_to "##{e.question}", diaries_path(q: e.id) %></p></div>
        <% end %>
      </div>
      
      
      
      <div id="contents">
        <% if flash[:notice] %>
        <%= flash[:notice] %>
        <% end %>
        
        <% if params[:each].nil? %>
          <% if params[:q].present? %>
            <% @diaries.each do |e| %>
              <% if params[:q].to_i == e.qid %>
                <div class="toukou"><div class="kakomi-box1">
                <header align="right"><%= e.date %>   <%=time_ago_in_words(e.created_at)%>前<br></header>
                <h3>
                <% user = User.find_by(id: e.user_id) %>
                <p　align="center"><%= user.name %>さん</p>
                <p>　</p>
                <%= e.title %>
                </h3>
                <p>　</p>
                <h4><%= safe_join(e.message.split("\n"),tag(:br)) %></h4>
                <p>
                <div class="img">
                <% if e.file.present? %>
                  <p>　</p>
                  <%= image_tag "/get_image/#{e.id}" %>
                <% end %>
                </div>
                </div>
                <% if session[:login_uid] == e.user_id %>
                  <p> </p>
                  <%= link_to '削除', "/diaries/#{e.id}", method: :delete, class: 'button04' %>
                  <%= link_to '編集', "/diaries/#{e.id}/edit", class: 'button04' %>
                <% end %>
                <% if session[:login_uid] == e.user_id %>
                  <p align="center"><%= link_to '自分の投稿のみ閲覧', diaries_path(each: e.user_id) %></p>
                <% else %>
                  <p align="center"><%= link_to 'このユーザの投稿のみ閲覧', diaries_path(each: e.user_id) %></p>
                <% end %>
                </p><br>
                </div>
              <% end %>
            <% end %>
            <%= link_to '戻る', diaries_path %>
          <%else%>
            <% @diaries.each do |e| %>
             <div class="toukou"><div class="kakomi-box1">
             <header align="right"><%= e.date %>   <%=time_ago_in_words(e.created_at)%>前<br></header>
             <h3>
             <% user = User.find_by(id: e.user_id) %>
             <p　align="center"><%= user.name %>さん</p>
             <p>　</p>
             <%= e.title %>
             </h3>
             <p>　</p>
             <h4><%= safe_join(e.message.split("\n"),tag(:br)) %></h4>
             <p>
             <div class="img">
             <% if e.file.present? %>
               <p>　</p>
               <%= image_tag "/get_image/#{e.id}" %>
             <% end %>
             </div>
             </div>
             <% if session[:login_uid] == e.user_id %>
                <p> </p>
                <%= link_to '削除', "/diaries/#{e.id}", method: :delete, class: 'button04' %>
                <%= link_to '編集', "/diaries/#{e.id}/edit", class: 'button04' %>
             <% end %>
             <% if session[:login_uid] == e.user_id %>
                <p align="center"><%= link_to '自分の投稿のみ閲覧', diaries_path(each: e.user_id) %></p>
             <% else %>
                <p align="center"><%= link_to 'このユーザの投稿のみ閲覧', diaries_path(each: e.user_id) %></p>
             <% end %>
             </p><br>
             </div>
            <% end %>
          <% end %>
        <% else %>
        <% @diaries.each do |e| %>
          <div class="toukou"><div class="kakomi-box1">
            <header align="right"><%= e.date %>   <%=time_ago_in_words(e.created_at)%>前<br></header>
            <h3>
            <% user = User.find_by(id: e.user_id) %>
            <p><%= user.name %>さん</p>
            <%= e.title %>
            </h3>
            <h4><%= e.message %></h4>
            <p>
              <div class="img">
              <% if e.file.present? %>
              <%= image_tag "/get_image/#{e.id}" %>
              <% end %>
              </div>
              </div>
                <p> </p>
                <% if session[:login_uid] == e.user_id %>
                <%= link_to '削除', "/diaries/#{e.id}", method: :delete, class: 'button04' %>
                <%= link_to '編集', "/diaries/#{e.id}/edit", class: 'button04' %>
              <% end %>
            </p><br>
          </div>
        <% end %>
        <%= link_to '戻る', diaries_path %>
      <% end %>
      </div>
      
    </div>
    
    <div id="footer">
       (c)copy right
    </div>
    
  </div> 

app/views/diaries/new.html.erb
<div id="wrapper">
        <div id="header">
           <%= image_tag 'rogo4.jpg', class: 'rogo' %>
        </div>
        
        <div id="main">
            <div id="menu">
                <p><%= link_to 'ホームへ', diaries_path, class: 'button02' %></p><br>
                <p><%= link_to 'ログアウト',  login_logout_path, class: 'button02' %></p><br>
            </div>
            
        　　<div id="contents">
                <% if @diary.errors.present? %>
                <h3>エラーがあります。</h3>
                <ul>
                <% @diary.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
                </ul>
                <% end %>
                
                <p><%= form_for @diary, url: {action: :create} do |f| %>
                <p><%= f.label :title, 'タイトル' %></p>
                <%= f.text_field :title, placeholder: "Title"%></p>
                <h4>お題：<%= f.label :message, Question.find_by(id: @question).question %>
                <%=link_to("/diaries/new") do %>
                 <div align="center"><button class="btn btn-secondary btn-lg" >お題を変更</button></div>
                <%end%>
                </h4>
                <p><%= f.text_area :message,size: "70x10",placeholder: "How was your day?" %></p>
                <p><%= f.label :file, 'ファイル' %></p>
                <p><%= f.file_field :file %></p>
                <%= f.hidden_field :qid, value: Question.find_by(id: @question).id %>
                <br>
                <p><%= f.submit '投稿する' %></p>
                <% end %>
            </div>
        </div>
        
        <div id="footer">
           (c)copy right
       </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/error.html.erb
<div id="wrapper">
    <div id="header">
       <%= image_tag 'rogo4.jpg', class: 'rogo' %>
    </div>
        
    <div id="main">
      ログイン失敗です
      <%= link_to '戻る', :back, class: 'button02' %>
    </div>
    
    <div id="footer">
      (c)copy right
    </div>
</div>

app/views/login/index.html.erb
<% if session[:login_id].nil? %>
<div id="wrapper">
        <div id="header">
            <%= image_tag 'rogo4.jpg', class: 'rogo' %>
        </div>
        
        <div id="main">
            <div id="menu">
                <p><%= link_to 'ログアウト',  login_logout_path, class: 'button02' %></p>
            </div>
        　　<div id="contents">
        　　  <h2>ようこそ</h2>
        　　    <% user = User.find_by(id: session[:login_uid]) %>
        　　    <p><%= user.name %>　さん　ログイン中です<p>
        　　    <p><%= link_to 'ホームへ',  diaries_path, class: 'button03' %></p>
              
            </div>
        </div>
        
        <div id="footer">
           (c)copy right
       </div>
</div>
<% else %>
<% redirect_to  login_login_page_path %>
<% end %>

app/views/login/login_page.html.erb
<div id="wrapper">
    <div id="header">
       <%= image_tag 'rogo4.jpg', class: 'rogo' %>
    </div>
        
    <div id="main">
      <div id="menu">
        <p><%= link_to '新規登録',  new_user_path, class: 'button02' %></p>
      </div>
            
      <div id="contents">
        <p><%= form_tag '/login/login_page', method: :post do %></p>
        <p><%= label_tag :name, 'ユーザー名' %></p>
        <p><%= text_field_tag :name %></p>
        <p><%= label_tag :email, 'メールアドレス' %></p>
        <p><%= text_field_tag :email %></p>
        <p><%= label_tag :password, 'パスワード' %></p>
        <p><%= password_field_tag :password %></p>
        <br>
        <p><%= submit_tag 'ログイン' %></p>
        <% end %> 
        
      </div>
    </div>
    
    <div id="footer">
      (c)copy right
    </div>
</div>

app/views/users/index.html.erb
<div id="wrapper">
    <div id="header">
       <%= image_tag 'rogo4.jpg', class: 'rogo' %>
    </div>
        
    <div id="main">
      <div id="menu">
        <p><%= link_to 'ホームへ', diaries_path, class: 'button02' %></p><br>
        <p><%= link_to 'ログアウト',  login_logout_path, class: 'button02' %></p><br>
      </div>
      
      <div id="contents">
        <% @users.each do |e| %>
          <% if session[:login_uid] == e.id %>
            <p>
            <%= e.name %>
            <%= e.email %>
            <%= link_to '削除', user_path(e), method: :delete %>
            </p>
          <% else %>
            <%= e.name %>
            <%= e.email %>
          <% end %>
        <% end %>
      </div>
      
    </div>
    
    <div id="footer">
      (c)copy right
    </div>
</div>

app/views/users/new.html.erb
<div id="wrapper">
    <div id="header">
       <%= image_tag 'rogo4.jpg', class: 'rogo' %>
    </div>
        
    <div id="main">
      <div id="menu">
        <p><%= link_to '戻る', :back, class: 'button02' %></p>
      </div>
      
      <div id="contents">
        <% if @user.errors.present? %>
        <h3>エラーがあります。</h3>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
        <% end %>
        
        <%= form_for @user, url: {action: :create} do |f| %>
          <p><%= f.label :name, 'ユーザー名' %></p>
          <p><%= f.text_field :name, placeholder: "User name" %></p> 
          <p><%= f.label :email, 'メールアドレス' %></p>
          <p><%= f.text_field :email, placeholder: "Email" %></p>
          <p><%= f.label :password, 'パスワード' %></p>
          <p><%= f.password_field :password, placeholder: "Password" %></p>
          <br>
          <p><%= f.submit '登録' %></p>
        <% end %>
      </div>
      
    </div>
    
    <div id="footer">
      (c)copy right
    </div>
</div>